version: "3"
services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./resources/docker/mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    networks:
      - backend
      - frontend
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db

  redis:
    image: redis:5.0
    volumes:
      - redis-data:/data
      - ./resources/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: always
    networks:
      - backend
    command: redis-server /usr/local/etc/redis/redis.conf
  
  php-fpm:
    build: ./resources/docker/php/image
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./resources/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/app:rw
    networks:
      - backend
    depends_on:
      - db
      - redis
  
  queue:
    build: ./resources/docker/queue/image
    restart: always
    volumes:
      - ./resources/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/app:rw
    networks:
      - backend
    depends_on:
      - db
      - redis
    command: /usr/local/bin/php /app/bin/yii queue/listen -v
  
  cron:
    build: ./resources/docker/cron/image
    restart: always
    volumes:
      - ./resources/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./resources/docker/cron/crontab:/etc/crontab:ro
      - ./:/app:rw
    networks:
      - backend
    depends_on:
      - db
      - redis
    command: bash -c "/usr/bin/crontab /etc/crontab && /usr/sbin/cron -f"

  web:
    image: nginx:1.17
    restart: always
    volumes:
      - ./resources/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./:/app:ro
      - ./runtime/logs:/app/runtime/logs:rw
    networks:
      - backend
      - frontend
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm

networks:
  frontend:
  backend:

volumes:
  db-data:
  redis-data:
