language: php


dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql
  - redis-server

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE yiitest;'
  - php bin/init --env=Development --overwrite=y
  - php bin/yii_test migrate/fresh --interactive=0
  - php bin/yii_test serve &

script:
  - vendor/bin/codecept run --coverage --coverage-xml

after_script:
    - wget -c https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
